apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todo-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: todo
  MYSQL_USER: todo
  MYSQL_PASSWORD: todo123
