apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo-app
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007

